-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 08, 2018 at 08:33 PM
-- Server version: 10.1.26-MariaDB
-- PHP Version: 7.1.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `culrav2k18`
--

-- --------------------------------------------------------

--
-- Table structure for table `mun_users`
--

CREATE TABLE `mun_users` (
  `Email` varchar(100) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Phone` varchar(13) NOT NULL,
  `Category` int(11) NOT NULL COMMENT 'Category for deciding fees',
  `College` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Table for users who are interested in MUN';

--
-- Dumping data for table `mun_users`
--

INSERT INTO `mun_users` (`Email`, `Name`, `Phone`, `Category`, `College`) VALUES
('abc@gmail.com', 'ABC', '9638527415', 1, 'IIIT Allahabad'),
('harshit@gmail.com', 'Harshit Shah', '789654321', 1, 'MNNIT Allahabad'),
('jashme69@gmail.com', 'Jyot Mehta', '7235857289', 1, 'MNNIT Allahabad'),
('jatintayal@gmail.com', 'Jatin Tayal', '7894561235', 0, 'DTU'),
('urjit@gmail.com', 'Urjit Patel', '1234567891', 0, 'MNNIT Allahabad'),
('yashchapani@gmail.com', 'Yash Chapani', '7418529631', 0, 'DU');

-- --------------------------------------------------------

--
-- Table structure for table `transac_details`
--

CREATE TABLE `transac_details` (
  `Email` varchar(100) NOT NULL COMMENT 'Foreign key of users',
  `Ref_no` varchar(100) NOT NULL COMMENT 'Merchant refno generated by our website',
  `Trans_no` varchar(100) NOT NULL COMMENT 'Payment ID generated by PAYU',
  `status` varchar(100) NOT NULL,
  `amount` int(11) NOT NULL,
  `productinfo` varchar(100) NOT NULL,
  `mode` varchar(100) NOT NULL COMMENT 'Mode of Payment',
  `bank_code` varchar(100) NOT NULL COMMENT 'PayU Money Generated Bank Code'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='This table is for payments done by users for MUN';

--
-- Dumping data for table `transac_details`
--

INSERT INTO `transac_details` (`Email`, `Ref_no`, `Trans_no`, `status`, `amount`, `productinfo`, `mode`, `bank_code`) VALUES
('harshit@gmail.com', '3cd12a12a1b608dd0a82', '52048', 'success', 1500, 'MUN Registration', 'CC', 'CC'),
('yashchapani@gmail.com', '5e40e8664ad91c059d73', '', 'pending', 1200, 'MUN Registration', '', ''),
('jashme69@gmail.com', 'bafc399b367d8bf3ed1e', '51965', 'success', 1500, 'MUN Registration', 'CC', 'CC'),
('abc@gmail.com', 'c0312c927f0d6507ff08', '52051', 'success', 1500, 'MUN Registration', 'CC', 'CC'),
('jatintayal@gmail.com', 'df46bc5b492b5faff25b', '', 'pending', 1200, 'MUN Registration', '', ''),
('urjit@gmail.com', 'fbf060b0d478a5343b00', '', 'pending', 1200, 'MUN Registration', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `mun_users`
--
ALTER TABLE `mun_users`
  ADD PRIMARY KEY (`Email`),
  ADD UNIQUE KEY `Phone` (`Phone`);

--
-- Indexes for table `transac_details`
--
ALTER TABLE `transac_details`
  ADD PRIMARY KEY (`Ref_no`),
  ADD KEY `FKEY` (`Email`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `transac_details`
--
ALTER TABLE `transac_details`
  ADD CONSTRAINT `User_Transac_Rel` FOREIGN KEY (`Email`) REFERENCES `mun_users` (`Email`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
